font:
  normal:
    family: hack
  bold:
    family: hack
  italic:
    family: hack
  size: 12.0
  offset:
    x: 0.0
    y: 0.0

hide_cursor_when_typing: true

visual_bell:
  animation: EaseOutSine
  duration: 100
