#!/bin/sh -f
# Configure wmii

MODKEY=Mod4

WMII_FOCUSCOLORS='#ffffff #86abd9 #8888cc'
WMII_BACKGROUND='#757575'
WMII_NORMCOLORS='#000000 #ffffea #bdb76b'

status() {
    echo -n  $(date +"%d/%m/%Y %T")
}

