#!/bin/sh
# Configure wmii

MODKEY=Mod4

WMII_FOCUSCOLORS='#ffffff #86abd9 #8888cc'
WMII_BACKGROUND='#757575'
WMII_NORMCOLORS='#000000 #ffffea #bdb76b'

status() {
    echo -n  $(date +"%d/%m/%Y %T")
}

# Column Rules
wmiir write /colrules <<!
/.*/ -> 50+50
!

# Tagging Rules
wmiir write /rules <<!
    /LibreOffice|pgAdmin/ floating=off
!

local_events() {
        cat <<'!'
# Keyboard resize
Key $MODKEY-Control-$LEFT
    wmiir xwrite /tag/sel/ctl grow sel sel right -1
Key $MODKEY-Control-$RIGHT
    wmiir xwrite /tag/sel/ctl grow sel sel right 1
Key $MODKEY-Control-$DOWN
    wmiir xwrite /tag/sel/ctl grow sel sel down 1
Key $MODKEY-Control-$UP
    wmiir xwrite /tag/sel/ctl grow sel sel down -1

Key $MODKEY-e
    pcmanfm &
!
}

