#!/bin/sh

. "$HOME/.bashrc.d/aliases"
xrdb ~/.Xresources

export XDG_CURRENT_DESKTOP=GNOME
export XDG_MENU_PREFIX="lxde-"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

setxkbmap -option ctrl:nocaps

if [ -s ~/.Xmodmap ]
then
    xmodmap ~/.Xmodmap
fi

if [ -e ~/.xstart.local ]
then
    ~/.xstart.local
fi

if [ -x /usr/bin/dunst ]
then
    killall notification-daemon &> /dev/null
    /usr/bin/dunst &
fi

function start()
{
    local command="$1"
    shift
    local arguments="$@"


    if [ -x "$command" ]
    then
        "$command" $arguments &
    fi
}

start /usr/bin/parcellite
start /usr/bin/nextcloud
start /usr/bin/urxvt --title term-scratchpad
start /usr/bin/xautolock -locker 'i3lock-fancy'
start /usr/bin/redshift
start /usr/bin/gpg-agent --daemon
start /usr/bin/keepassxc
start /usr/bin/udiskie --tray --use-udisks2

i3 --force-xinerama
