#!/bin/sh

. "$HOME/.bashrc.d/aliases"
setxkbmap fr bepo

export XDG_CURRENT_DESKTOP=GNOME
export XDG_MENU_PREFIX="lxde-"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

setxkbmap -option ctrl:nocaps

if [ -s ~/.Xmodmap ]
then
    xmodmap ~/.Xmodmap
fi

if [ -x /usr/bin/dunst ]
then
    killall notification-daemon &> /dev/null
    /usr/bin/dunst &
fi

/usr/bin/dex -a

if [ -e ~/.xstart.local ]
then
    ~/.xstart.local
fi

dbus-run-session i3
