#!/bin/bash

# author: Duane Johnson
# email: duane.johnson@gmail.com
# date: 2008 Jun 12
# license: MIT
#
# Based on discussion at http://kerneltrap.org/mailarchive/git/2007/11/12/406496

. git-sh-setup

pushd . >/dev/null

# Find base of git directory
while [ ! -d .git ] && [ ! `pwd` = "/" ]; do cd ..; done

# Show various information about this git directory
if [ -d .git ]; then
  echo "== Remote URL:
$(git remote -v)

== Remote Branches:
$(git branch -r --color)

== Local Branches:
$(git branch -vv --color)

== Configuration (.git/config)
$(cat .git/config)

== Most Recent Commit
$(git --no-pager log --max-count=1 --color)

Type 'git log' for more commits, or 'git show' for full commit details." | git_pager
else
  echo "Not a git repository."
fi

popd >/dev/null
