#!/bin/bash

main() {
    local fn=${1-short}

    case $fn in
        "dialog")
            dialog
        ;;
        "short")
            short
        ;;
    esac
}

short() {
    n=$(t | head -n -2 | wc -l)
    pri=$(t listpri | head --lines -2 | sed  's/.* (\([A-Z]\)) .*/\1/'  | sort | head -1)

    case $pri in
        "A")
            color="#BF616A"
        ;;
        "B")
            color="#EBCB8B"
        ;;
        "C")
            color="#88C0D0"
        ;;
        *)
            color="#FFFFFF"
        ;;
    esac

    if [[ "$n" == 0 ]]
    then
        n='-'
    fi

    echo -n "(label :style 'color: $color' :text ' $n')"
}

dialog() {
    export GTK_THEME=Arc-Darker:dark
    local todo=$(t | head -n -2)

    if [[ -n "$todo" ]]
    then
        echo "$todo" | yad --list --column=task --no-headers --undecorated --button yad-close:0 --mouse --width=500 --height=300
    fi
}

main $*
