#!/bin/bash

set -euo pipefail

main() {
    local fn=${1-short}

    case $fn in
        "dialog")
            dialog
        ;;
        "tooltip")
            tooltip
        ;;
        "short")
            short
        ;;
    esac
}

short() {
    meteo short
}

tooltip() {
    meteo tooltip
}

dialog() {
    xdg-open $(meteo dialog)
}

main $*
