#!/bin/bash

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

# full text
echo "ν $load"

# short text
echo "ν $load"

# color if load is too high
if [ $(awk 'BEGIN{ print "'$cpus'"<="'$load'" }') -eq 1 ]; then
        echo "#FF0000"
fi
