#!/bin/bash

set -euo pipefail

main() {
    local fn=${1-short}

    case $fn in
        "dialog")
            dialog
        ;;
        "short")
            short
        ;;
    esac
}

short() {
    network short
    inotifywait --event close_write --monitor /proc/net/fib_trie | while read
    do
        network short
    done
}

dialog() {
    export GTK_THEME=Arc-Darker:dark

    local ips=$(network dialog)

    if [[ -n "$ips" ]]
    then
        echo "$ips" | GDK_BACKEND=x11 yad --list --tree --tree-expanded --column=ip --no-headers --undecorated --button yad-close:0 --mouse --width=500 --height=300
    fi
}

main $*
