#!/bin/bash

set -euo pipefail

main() {
    local fn=${1-short}

    case $fn in
        "dialog")
            dialog
        ;;
        "short")
            short
        ;;
        "tooltip")
            tooltip
        ;;
    esac
}

short() {
    while true
    do
        meteo short
        sleep 2m
    done
}

tooltip() {
    while true
    do
        meteo tooltip
        sleep 2m
    done
}

dialog() {
    xdg-open $(meteo dialog)
}

main $*
