#!/bin/bash

set -euo pipefail

readonly SRCDIR=$(cd "$(dirname "$0")" && pwd)

main()
{
    local version=${1-$(wget -O - -q https://api.github.com/repos/ghacksuserjs/ghacks-user.js/releases/latest | jq --raw-output .tag_name)}

    wget -O "$SRCDIR/user.js" "https://github.com/ghacksuserjs/ghacks-user.js/raw/$version/user.js"

    sed -i -e "/END:/r $SRCDIR/user-overrides.js" -e 'x;$G' "$SRCDIR/user.js"
}

main
