#!/bin/bash

main() {
    local fn=${1-short}

    case $fn in
        "dialog")
            dialog
        ;;
        "short")
            short
        ;;
    esac
}

short() {
    next_appointment short 2> /dev/null || echo '×' &
    next_appointment dialog > /tmp/next_appointment 2> /dev/null &
    wait
}

dialog() {
    export GTK_THEME=Arc-Darker:dark

    local events=$(cat /tmp/next_appointment)

    if [[ -n "$events" ]]
    then
        echo "$events" | yad --list --tree --tree-expanded --expand-column=1 --column=event --column=img --column=url:HD --dclick-action='bash -c "xdg_open %s"' --no-headers --undecorated --button yad-close:0 --mouse --width=500 --height=300
    fi
}

xdg_open() {
    local url=$3

    if [[ -n "$url" ]]
    then
        xdg-open "$url"
    fi
}
export -f xdg_open

main $*
